(() => {
  "use strict";

  const rows = [
    ["Home", "Inicio", "Inici", "Accueil", "Startseite", "首页", "ホーム"],
    ["Extensions", "Extensiones", "Extensions", "Extensions", "Erweiterungen", "扩展程序", "拡張機能"],
    ["All tools", "Todas las herramientas", "Totes les eines", "Tous les outils", "Alle Tools", "全部工具", "すべてのツール"],
    ["Privacy", "Privacidad", "Privacitat", "Confidentialité", "Datenschutz", "隐私", "プライバシー"],
    ["Support", "Soporte", "Suport", "Assistance", "Support", "支持", "サポート"],
    ["Productivity Suite for Chrome", "Productivity Suite para Chrome", "Productivity Suite per a Chrome", "Productivity Suite pour Chrome", "Productivity Suite für Chrome", "Chrome 效率套件", "Chrome 生産性スイート"],
    ["Keep your research and recurring forms under control.", "Mantén bajo control tu investigación y tus formularios recurrentes.", "Mantén sota control la recerca i els formularis recurrents.", "Gardez vos recherches et vos formulaires récurrents sous contrôle.", "Behalten Sie Ihre Recherche und wiederkehrende Formulare im Griff.", "掌控你的研究资料和重复填写的表单。", "リサーチと繰り返し使うフォームを管理しましょう。"],
    ["Two focused browser extensions that remove busywork without taking control away from you. Your packs and profiles stay local in Chrome.", "Dos extensiones de navegador centradas en eliminar trabajo repetitivo sin quitarte el control. Tus packs y perfiles permanecen en Chrome.", "Dues extensions de navegador pensades per eliminar feina repetitiva sense treure't el control. Els teus packs i perfils es queden a Chrome.", "Deux extensions ciblées qui éliminent le travail répétitif sans vous retirer le contrôle. Vos packs et profils restent dans Chrome.", "Zwei fokussierte Browser-Erweiterungen, die Routinearbeit abnehmen, ohne Ihnen die Kontrolle zu nehmen. Ihre Pakete und Profile bleiben in Chrome.", "两款专注的浏览器扩展，帮你减少重复工作，同时保持完全掌控。你的资料包和档案都保留在 Chrome 中。", "主導権を失わずに単純作業を減らす、2つのブラウザー拡張機能です。パックとプロフィールは Chrome 内に保存されます。"],
    ["Local-first by default", "Local por defecto", "Local per defecte", "Local par défaut", "Standardmäßig lokal", "默认本地存储", "ローカル優先"],
    ["No account for core workflows", "Sin cuenta para las funciones principales", "Sense compte per a les funcions principals", "Aucun compte pour les fonctions essentielles", "Kein Konto für Kernfunktionen", "核心功能无需账户", "主要機能はアカウント不要"],
    ["You approve every action", "Tú apruebas cada acción", "Tu aproves cada acció", "Vous approuvez chaque action", "Sie genehmigen jede Aktion", "每项操作都由你确认", "すべての操作をあなたが承認します"],
    ["Explore the tools", "Explora las herramientas", "Explora les eines", "Découvrir les outils", "Tools entdecken", "探索工具", "ツールを見る"],
    ["How it works", "Cómo funciona", "Com funciona", "Comment ça marche", "So funktioniert es", "工作原理", "仕組み"],
    ["Inside the suite", "Dentro de la suite", "Dins de la suite", "Dans la suite", "In der Suite", "套件包含", "スイートの内容"],
    ["Built for focused study, applications and everyday admin.", "Pensado para estudiar con foco, solicitudes y gestiones diarias.", "Pensat per estudiar amb focus, sol·licituds i gestions diàries.", "Conçu pour les études, les candidatures et les démarches quotidiennes.", "Für konzentriertes Lernen, Bewerbungen und täglichen Papierkram.", "专为专注学习、申请和日常事务而设计。", "集中した学習、応募、日々の事務作業のために。"],
    ["Chrome extensions", "Extensiones de Chrome", "Extensions de Chrome", "Extensions Chrome", "Chrome-Erweiterungen", "Chrome 扩展程序", "Chrome 拡張機能"],
    ["Small tools. A more organised workflow.", "Herramientas pequeñas. Un flujo de trabajo más ordenado.", "Eines petites. Un flux de treball més ordenat.", "De petits outils. Un flux de travail plus organisé.", "Kleine Tools. Ein besser organisierter Workflow.", "小工具，更有序的工作流程。", "小さなツールで、より整ったワークフローを。"],
    ["Keep every useful source together.", "Mantén juntas todas las fuentes útiles.", "Mantén juntes totes les fonts útils.", "Gardez toutes vos sources utiles au même endroit.", "Halten Sie alle nützlichen Quellen zusammen.", "将所有有用的资料来源集中在一起。", "役立つ情報源をすべてまとめておけます。"],
    ["Fill forms on your terms.", "Rellena formularios a tu manera.", "Omple formularis a la teva manera.", "Remplissez les formulaires à votre façon.", "Formulare nach Ihren Vorstellungen ausfüllen.", "按你的方式填写表单。", "あなたのやり方でフォームを入力。"],
    ["Explore Research Packs", "Explorar Research Packs", "Explora Research Packs", "Découvrir Research Packs", "Research Packs entdecken", "探索 Research Packs", "Research Packs を見る"],
    ["Explore AutoFill Pro", "Explorar AutoFill Pro", "Explora AutoFill Pro", "Découvrir AutoFill Pro", "AutoFill Pro entdecken", "探索 AutoFill Pro", "AutoFill Pro を見る"],
    ["Designed around control", "Diseñado para que tengas el control", "Dissenyat perquè tinguis el control", "Conçu autour de votre contrôle", "Für Ihre Kontrolle entwickelt", "为你的掌控而设计", "あなたのコントロールを中心に設計"],
    ["Useful in minutes, not another system to manage.", "Útil en minutos, no otro sistema que gestionar.", "Útil en minuts, no un altre sistema per gestionar.", "Utile en quelques minutes, pas un autre système à gérer.", "In Minuten nützlich, kein weiteres System zum Verwalten.", "几分钟即可上手，而不是又一个要管理的系统。", "数分で役立ち、管理すべき新しいシステムにはなりません。"],
    ["Choose the right tool", "Elige la herramienta adecuada", "Tria l'eina adequada", "Choisissez le bon outil", "Wählen Sie das passende Tool", "选择合适的工具", "適切なツールを選ぶ"],
    ["Keep it local", "Mantenlo local", "Mantén-ho local", "Gardez-le local", "Lokal behalten", "保留在本地", "ローカルに保つ"],
    ["Stay in control", "Mantén el control", "Mantén el control", "Gardez le contrôle", "Behalten Sie die Kontrolle", "保持掌控", "コントロールを保つ"],
    ["Privacy by design", "Privacidad desde el diseño", "Privacitat des del disseny", "Confidentialité dès la conception", "Datenschutz durch Design", "隐私保护设计", "プライバシーを設計に組み込む"],
    ["Your study data stays with you.", "Tus datos de estudio se quedan contigo.", "Les teves dades d'estudi es queden amb tu.", "Vos données d'étude restent avec vous.", "Ihre Studiendaten bleiben bei Ihnen.", "你的学习数据始终属于你。", "学習データはあなたの手元に残ります。"],
    ["Read privacy summary", "Leer resumen de privacidad", "Llegiu el resum de privacitat", "Lire le résumé de confidentialité", "Datenschutz-Zusammenfassung lesen", "查看隐私摘要", "プライバシー概要を読む"],
    ["Turn scattered tabs into useful research context.", "Convierte pestañas dispersas en contexto de investigación útil.", "Converteix pestanyes disperses en context de recerca útil.", "Transformez des onglets dispersés en contexte de recherche utile.", "Machen Sie aus verstreuten Tabs nützlichen Recherchekontext.", "将分散的标签页变成有用的研究资料。", "散らばったタブを役立つリサーチ情報に変えます。"],
    ["See features", "Ver funciones", "Veure funcions", "Voir les fonctionnalités", "Funktionen ansehen", "查看功能", "機能を見る"],
    ["Save useful tabs", "Guarda pestañas útiles", "Desa pestanyes útils", "Enregistrez les onglets utiles", "Nützliche Tabs speichern", "保存有用的标签页", "役立つタブを保存"],
    ["Find context", "Encuentra el contexto", "Troba el context", "Retrouvez le contexte", "Kontext finden", "找到相关内容", "文脈を見つける"],
    ["Export locally", "Exporta en local", "Exporta en local", "Exportez localement", "Lokal exportieren", "本地导出", "ローカルにエクスポート"],
    ["A calmer research workflow", "Un flujo de investigación más tranquilo", "Un flux de recerca més tranquil", "Un flux de recherche plus serein", "Ein ruhigerer Recherche-Workflow", "更从容的研究流程", "より落ち着いたリサーチの流れ"],
    ["From open tabs to a source library you can use.", "De pestañas abiertas a una biblioteca de fuentes que puedes usar.", "De pestanyes obertes a una biblioteca de fonts que pots utilitzar.", "Des onglets ouverts à une bibliothèque de sources exploitable.", "Von offenen Tabs zu einer Quellenbibliothek, die Sie nutzen können.", "从打开的标签页到真正可用的资料库。", "開いたタブを、使える情報源ライブラリへ。"],
    ["No account required for your packs.", "No necesitas cuenta para tus packs.", "No cal cap compte per als teus packs.", "Aucun compte requis pour vos packs.", "Kein Konto für Ihre Pakete erforderlich.", "你的资料包无需账户。", "パックにアカウントは必要ありません。"],
    ["Fill recurring forms with your data, on your terms.", "Rellena formularios recurrentes con tus datos, a tu manera.", "Omple formularis recurrents amb les teves dades, a la teva manera.", "Remplissez les formulaires récurrents avec vos données, à votre façon.", "Wiederkehrende Formulare mit Ihren Daten nach Ihren Vorstellungen ausfüllen.", "按你的方式用自己的数据填写重复表单。", "あなたのデータで、あなたのやり方で繰り返し使うフォームを入力。"],
    ["Built for repeat admin", "Pensado para gestiones repetitivas", "Pensat per a gestions repetitives", "Conçu pour les démarches répétitives", "Für wiederkehrende Verwaltung", "专为重复事务而设计", "繰り返しの事務作業のために"],
    ["Keep your details ready, without handing them over.", "Ten tus datos listos sin entregárselos a nadie.", "Tingues les teves dades preparades sense cedir-les a ningú.", "Gardez vos informations prêtes sans les céder.", "Halten Sie Ihre Angaben bereit, ohne sie aus der Hand zu geben.", "随时准备好你的信息，但不把它交出去。", "情報を手元に準備しながら、渡してしまわない。"],
    ["Flexible profiles", "Perfiles flexibles", "Perfils flexibles", "Profils flexibles", "Flexible Profile", "灵活的档案", "柔軟なプロフィール"],
    ["Modern forms", "Formularios modernos", "Formularis moderns", "Formulaires modernes", "Moderne Formulare", "现代化表单", "最新のフォーム"],
    ["Local by default", "Local por defecto", "Local per defecte", "Local par défaut", "Standardmäßig lokal", "默认本地存储", "ローカルが標準"],
    ["Review before submitting", "Revisa antes de enviar", "Revisa abans d'enviar", "Vérifiez avant d'envoyer", "Vor dem Absenden prüfen", "提交前检查", "送信前に確認"],
    ["AutoFill Pro never sends a form for you.", "AutoFill Pro nunca envía un formulario por ti.", "AutoFill Pro mai envia cap formulari per tu.", "AutoFill Pro n'envoie jamais un formulaire à votre place.", "AutoFill Pro sendet niemals ein Formular für Sie ab.", "AutoFill Pro 绝不会替你提交表单。", "AutoFill Pro が代わりにフォームを送信することはありません。"],
    ["Local-first by default.", "Local por defecto.", "Local per defecte.", "Local par défaut.", "Standardmäßig lokal.", "默认本地存储。", "ローカル優先が標準です。"],
    ["What stays local", "Qué se queda en local", "Què es queda en local", "Ce qui reste local", "Was lokal bleibt", "哪些数据保留在本地", "ローカルに残るもの"],
    ["Research Packs stores pack names, URLs, notes, tags and dates in Chrome local extension storage. AutoFill Pro stores profiles, local preferences, website rules containing a domain, optional path, selected profile and automation mode, a limited fill diagnostic history, and learned field corrections containing the domain, an anonymous field fingerprint and the associated profile field. Rules, diagnostics and corrections never store entered values or page contents.", "Research Packs guarda nombres de packs, URLs, notas, etiquetas y fechas en el almacenamiento local de Chrome. AutoFill Pro guarda perfiles, preferencias locales, reglas por web con dominio, ruta opcional, perfil elegido y modo de automatización, un historial limitado de diagnóstico y correcciones aprendidas con el dominio, una huella anónima del campo y el dato del perfil asociado. Las reglas, el diagnóstico y las correcciones nunca guardan valores introducidos ni contenido de la página.", "Research Packs desa noms de packs, URLs, notes, etiquetes i dates a l’emmagatzematge local de Chrome. AutoFill Pro desa perfils, preferències locals, regles web amb domini, ruta opcional, perfil triat i mode d’automatització, un historial limitat de diagnòstic i correccions apreses amb el domini, una empremta anònima del camp i la dada del perfil associada. Les regles, el diagnòstic i les correccions mai desen valors introduïts ni contingut de la pàgina.", "Research Packs stocke les noms des packs, les URL, les notes, les étiquettes et les dates dans le stockage local de Chrome. AutoFill Pro stocke les profils, les préférences locales, les règles de site avec domaine, chemin facultatif, profil choisi et mode d’automatisation, un historique de diagnostic limité et les corrections mémorisées avec le domaine, une empreinte anonyme du champ et la donnée de profil associée. Les règles, diagnostics et corrections ne stockent jamais les valeurs saisies ni le contenu des pages.", "Research Packs speichert Paketnamen, URLs, Notizen, Tags und Datumsangaben lokal in Chrome. AutoFill Pro speichert Profile, lokale Einstellungen, Website-Regeln mit Domain, optionalem Pfad, gewähltem Profil und Automatisierungsmodus, einen begrenzten Diagnoseverlauf und gelernte Korrekturen mit Domain, anonymem Feldfingerabdruck und zugeordnetem Profilfeld. Regeln, Diagnosen und Korrekturen speichern niemals eingegebene Werte oder Seiteninhalte.", "Research Packs 在 Chrome 本地扩展存储中保存资料包名称、网址、笔记、标签和日期。AutoFill Pro 保存档案、本地偏好、包含域名、可选路径、所选档案和自动化模式的网站规则、有限的填写诊断历史，以及包含域名、匿名字段指纹和关联档案字段的学习更正。规则、诊断和更正绝不保存输入值或页面内容。", "Research Packs はパック名、URL、メモ、タグ、日付を Chrome のローカル拡張機能ストレージに保存します。AutoFill Pro はプロフィール、ローカル設定、ドメイン・任意のパス・選択したプロフィール・自動化モードを含むサイトルール、限定的な入力診断履歴、ドメイン・匿名の項目フィンガープリント・関連付けたプロフィール項目を含む学習済み修正を保存します。ルール、診断、修正は入力値やページ内容を保存しません。"],
    ["Research Packs stores pack names, URLs, notes, tags, domains, capture dates and optional descriptive source metadata in Chrome local extension storage. AutoFill Pro stores profiles, local preferences, website rules containing a domain, optional path, selected profile and automation mode, a limited fill diagnostic history, and learned field corrections containing the domain, an anonymous field fingerprint and the associated profile field. Rules, diagnostics and corrections never store entered values or full page contents.", "Research Packs guarda nombres de packs, URLs, notas, etiquetas, dominios, fechas de captura y metadatos descriptivos opcionales de las fuentes en el almacenamiento local de Chrome. AutoFill Pro guarda perfiles, preferencias locales, reglas por web, un historial limitado de diagnóstico y correcciones aprendidas. Las reglas, diagnósticos y correcciones nunca guardan valores introducidos ni el contenido completo de las páginas.", "Research Packs desa noms de packs, URLs, notes, etiquetes, dominis, dates de captura i metadades descriptives opcionals de les fonts a l’emmagatzematge local de Chrome. AutoFill Pro desa perfils, preferències locals, regles web, un historial limitat de diagnòstic i correccions apreses. Les regles, diagnòstics i correccions mai desen valors introduïts ni el contingut complet de les pàgines.", "Research Packs stocke dans Chrome les noms des dossiers, URL, notes, étiquettes, domaines, dates de capture et métadonnées descriptives facultatives des sources. AutoFill Pro stocke les profils, préférences locales, règles de site, un historique de diagnostic limité et les corrections mémorisées. Les règles, diagnostics et corrections ne stockent jamais les valeurs saisies ni le contenu complet des pages.", "Research Packs speichert Paketnamen, URLs, Notizen, Tags, Domains, Erfassungsdaten und optionale beschreibende Quellenmetadaten lokal in Chrome. AutoFill Pro speichert Profile, lokale Einstellungen, Website-Regeln, einen begrenzten Diagnoseverlauf und gelernte Korrekturen. Regeln, Diagnosen und Korrekturen speichern niemals eingegebene Werte oder vollständige Seiteninhalte.", "Research Packs 在 Chrome 本地存储资料包名称、网址、笔记、标签、域名、捕获日期和可选的描述性来源元数据。AutoFill Pro 存储档案、本地偏好、网站规则、有限的诊断历史和学习更正。规则、诊断和更正绝不保存输入值或完整网页内容。", "Research Packs はパック名、URL、メモ、タグ、ドメイン、取得日、任意の説明メタデータを Chrome 内に保存します。AutoFill Pro はプロフィール、ローカル設定、サイトルール、限定的な診断履歴、学習済み修正を保存します。ルール、診断、修正が入力値やページ全体の内容を保存することはありません。"],
    ["When a Pro user enables enriched source metadata, Research Packs asks Chrome for optional access only to the selected sites. Author, description, publication date, site, language, content type, DOI and canonical URL are read and processed locally. This access can be declined, and no page content or metadata is sent to Productivity Suite servers.", "Cuando un usuario Pro activa los metadatos enriquecidos, Research Packs pide a Chrome acceso opcional solo a los sitios seleccionados. El autor, la descripción, la fecha de publicación, el sitio, el idioma, el tipo de contenido, el DOI y la URL canónica se leen y procesan localmente. El acceso puede rechazarse y ningún contenido o metadato se envía a los servidores de Productivity Suite.", "Quan un usuari Pro activa les metadades enriquides, Research Packs demana a Chrome accés opcional només als llocs seleccionats. L’autor, la descripció, la data de publicació, el lloc, l’idioma, el tipus de contingut, el DOI i l’URL canònica es llegeixen i processen localment. L’accés es pot rebutjar i no s’envia cap contingut ni metadada als servidors de Productivity Suite.", "Lorsqu’un utilisateur Pro active les métadonnées enrichies, Research Packs demande à Chrome un accès facultatif uniquement aux sites sélectionnés. L’auteur, la description, la date de publication, le site, la langue, le type de contenu, le DOI et l’URL canonique sont lus et traités localement. Cet accès peut être refusé et aucun contenu ni métadonnée n’est envoyé aux serveurs de Productivity Suite.", "Wenn ein Pro-Nutzer erweiterte Metadaten aktiviert, fragt Research Packs Chrome nur nach optionalem Zugriff auf die ausgewählten Websites. Autor, Beschreibung, Veröffentlichungsdatum, Website, Sprache, Inhaltstyp, DOI und kanonische URL werden lokal gelesen und verarbeitet. Der Zugriff kann abgelehnt werden; Seiteninhalte und Metadaten werden nicht an Productivity-Suite-Server gesendet.", "当专业版用户启用丰富元数据时，Research Packs 只会请求 Chrome 访问所选网站。作者、描述、发布日期、网站、语言、内容类型、DOI 和规范网址均在本地读取和处理。用户可以拒绝此访问，网页内容或元数据不会发送到 Productivity Suite 服务器。", "Pro ユーザーが詳細メタデータを有効にすると、Research Packs は選択したサイトへの任意アクセスのみを Chrome に求めます。著者、説明、公開日、サイト、言語、種類、DOI、正規 URL はローカルで読み取り処理されます。アクセスは拒否でき、ページ内容やメタデータが Productivity Suite のサーバーへ送信されることはありません。"],
    ["When a Pro user opens Reading View, Research Packs requests optional access only to that source. The readable article text is processed temporarily on the device, is never stored or uploaded, and is removed from memory when the view closes. A closed source may be loaded in a temporary background tab that is closed automatically after extraction.", "Cuando un usuario Pro abre la Vista de lectura, Research Packs solicita acceso opcional solo a esa fuente. El texto legible se procesa temporalmente en el dispositivo, nunca se guarda ni se sube y se elimina de la memoria al cerrar la vista. Una fuente cerrada puede cargarse en una pestaña temporal en segundo plano que se cierra automáticamente después de la extracción.", "Quan un usuari Pro obre la Vista de lectura, Research Packs sol·licita accés opcional només a aquella font. El text llegible es processa temporalment al dispositiu, mai no es desa ni es puja i s’elimina de la memòria en tancar la vista. Una font tancada es pot carregar en una pestanya temporal en segon pla que es tanca automàticament després de l’extracció.", "Lorsqu’un utilisateur Pro ouvre le mode lecture, Research Packs demande un accès facultatif uniquement à cette source. Le texte lisible est traité temporairement sur l’appareil, jamais enregistré ni téléversé, puis supprimé de la mémoire à la fermeture. Une source fermée peut être chargée dans un onglet temporaire en arrière-plan, fermé automatiquement après l’extraction.", "Wenn ein Pro-Nutzer die Leseansicht öffnet, fordert Research Packs optionalen Zugriff nur auf diese Quelle an. Der lesbare Text wird vorübergehend auf dem Gerät verarbeitet, nie gespeichert oder hochgeladen und beim Schließen aus dem Speicher entfernt. Eine geschlossene Quelle kann in einem temporären Hintergrund-Tab geladen werden, der nach der Extraktion automatisch geschlossen wird.", "当专业版用户打开阅读视图时，Research Packs 只请求访问该来源。可读正文仅在设备上临时处理，不会保存或上传，并会在关闭视图时从内存中移除。未打开的来源可能会在临时后台标签页中加载，提取后自动关闭。", "Pro ユーザーが読書ビューを開くと、Research Packs はその情報源への任意アクセスのみを求めます。本文は端末上で一時処理され、保存・アップロードされず、ビューを閉じるとメモリから削除されます。閉じている情報源は一時的なバックグラウンドタブで読み込まれ、抽出後に自動的に閉じられる場合があります。"],
    ["Sign-in, authentication, SSO/OAuth and other restricted pages are excluded from metadata reading and are saved with basic tab information only. They never block metadata capture for other selected sources.", "Las páginas de inicio de sesión, autenticación, SSO/OAuth y otras páginas restringidas se excluyen de la lectura de metadatos y solo se guardan con la información básica de la pestaña. Nunca bloquean la captura de las demás fuentes seleccionadas.", "Les pàgines d’inici de sessió, autenticació, SSO/OAuth i altres pàgines restringides s’exclouen de la lectura de metadades i només es desen amb la informació bàsica de la pestanya. Mai bloquegen la captura de les altres fonts seleccionades.", "Les pages de connexion, d’authentification, SSO/OAuth et autres pages restreintes sont exclues de la lecture des métadonnées et enregistrées uniquement avec les informations de base de l’onglet. Elles ne bloquent jamais la capture des autres sources sélectionnées.", "Anmelde-, Authentifizierungs-, SSO/OAuth- und andere eingeschränkte Seiten werden von der Metadatenerfassung ausgeschlossen und nur mit grundlegenden Tab-Informationen gespeichert. Sie blockieren niemals die Erfassung anderer ausgewählter Quellen.", "登录、身份验证、SSO/OAuth 和其他受限页面不会读取元数据，只保存基本标签页信息。它们不会阻止捕获其他所选来源的元数据。", "ログイン、認証、SSO/OAuth、その他の制限ページはメタデータ読み取りの対象外となり、基本的なタブ情報のみ保存されます。他の選択した情報源の取得を妨げることはありません。"],
    ["What may be transmitted", "Qué puede transmitirse", "Què es pot transmetre", "Ce qui peut être transmis", "Was übertragen werden kann", "可能传输的内容", "送信される可能性があるもの"],
    ["Contact", "Contacto", "Contacte", "Contact", "Kontakt", "联系", "お問い合わせ"],
    ["How can we help?", "¿Cómo podemos ayudarte?", "Com et podem ajudar?", "Comment pouvons-nous vous aider ?", "Wie können wir helfen?", "我们如何帮助你？", "どのようにお手伝いできますか？"],
    ["Email support", "Escribir a soporte", "Escriure a suport", "Contacter l'assistance", "Support kontaktieren", "发送支持邮件", "サポートにメールする"],
    ["That page does not exist.", "Esa página no existe.", "Aquesta pàgina no existeix.", "Cette page n'existe pas.", "Diese Seite existiert nicht.", "该页面不存在。", "このページは存在しません。"],
    ["Return to Productivity Suite and choose a product.", "Vuelve a Productivity Suite y elige un producto.", "Torna a Productivity Suite i tria un producte.", "Retournez à Productivity Suite et choisissez un produit.", "Kehren Sie zu Productivity Suite zurück und wählen Sie ein Produkt.", "返回 Productivity Suite 并选择一个产品。", "Productivity Suite に戻って製品を選択してください。"],
    ["Go home", "Ir al inicio", "Ves a l'inici", "Retour à l'accueil", "Zur Startseite", "返回首页", "ホームへ戻る"],
    ["Turn selected tabs into organised packs with notes, tags and local exports.", "Convierte pestañas seleccionadas en packs organizados con notas, etiquetas y exportaciones locales.", "Converteix pestanyes seleccionades en packs organitzats amb notes, etiquetes i exportacions locals.", "Transformez les onglets sélectionnés en packs organisés avec notes, étiquettes et exports locaux.", "Verwandeln Sie ausgewählte Tabs in organisierte Pakete mit Notizen, Tags und lokalen Exporten.", "将选中的标签页整理成带有笔记、标签和本地导出的资料包。", "選択したタブを、メモ・タグ・ローカルエクスポート付きの整理されたパックにします。"],
    ["Use editable profiles and choose whether to review or safely fill recognised fields automatically.", "Usa perfiles editables y elige entre revisar o rellenar automáticamente los campos reconocidos de forma segura.", "Utilitza perfils editables i tria entre revisar o emplenar automàticament els camps reconeguts de manera segura.", "Utilisez des profils modifiables et choisissez de vérifier ou de remplir automatiquement et en toute sécurité les champs reconnus.", "Nutzen Sie bearbeitbare Profile und wählen Sie, ob erkannte Felder geprüft oder sicher automatisch ausgefüllt werden.", "使用可编辑档案，并选择检查或安全地自动填写已识别字段。", "編集可能なプロフィールを使い、認識した項目を確認するか安全に自動入力するかを選べます。"],
    ["Start with the task that takes too much of your attention today. Each extension has one clear job and keeps its data in your browser.", "Empieza por la tarea que hoy te quita demasiada atención. Cada extensión tiene una función clara y mantiene sus datos en tu navegador.", "Comença per la tasca que avui et pren massa atenció. Cada extensió té una funció clara i conserva les dades al navegador.", "Commencez par la tâche qui vous prend trop d'attention aujourd'hui. Chaque extension a un rôle clair et conserve ses données dans votre navigateur.", "Beginnen Sie mit der Aufgabe, die heute zu viel Aufmerksamkeit kostet. Jede Erweiterung hat eine klare Aufgabe und behält ihre Daten im Browser.", "从今天最占用你注意力的任务开始。每个扩展都有明确职责，并将数据保留在浏览器中。", "今日あなたの注意を奪っている作業から始めましょう。各拡張機能には明確な役割があり、データはブラウザー内に残ります。"],
    ["Save selected tabs as local research packs. Add notes, reopen context later and export your work from one dashboard.", "Guarda pestañas seleccionadas como packs de investigación locales. Añade notas, recupera el contexto después y exporta tu trabajo desde un solo panel.", "Desa pestanyes seleccionades com a packs de recerca locals. Afegeix notes, recupera el context més tard i exporta la feina des d'un sol tauler.", "Enregistrez les onglets sélectionnés comme packs de recherche locaux. Ajoutez des notes, retrouvez le contexte plus tard et exportez votre travail depuis un seul tableau de bord.", "Speichern Sie ausgewählte Tabs als lokale Recherchepakete. Fügen Sie Notizen hinzu, öffnen Sie den Kontext später erneut und exportieren Sie Ihre Arbeit aus einem Dashboard.", "将选中的标签页保存为本地研究资料包。添加笔记，稍后恢复上下文，并从一个面板导出你的工作。", "選択したタブをローカルのリサーチパックとして保存。メモを追加し、後で文脈を再び開き、1つのダッシュボードからエクスポートできます。"],
    ["Create profiles locally, link them to websites if you wish, and stay in control before submitting anything yourself.", "Crea perfiles en local, vincúlalos a webs si quieres y mantén el control antes de enviar nada por tu cuenta.", "Crea perfils en local, vincula'ls a webs si vols i mantén el control abans d'enviar res.", "Créez des profils localement, liez-les aux sites si vous le souhaitez et gardez le contrôle avant tout envoi.", "Erstellen Sie Profile lokal, verknüpfen Sie sie bei Bedarf mit Websites und behalten Sie vor dem Absenden die Kontrolle.", "在本地创建档案，可按需关联网站，并在自行提交前保持掌控。", "プロフィールをローカルで作成し、必要ならサイトに関連付け、送信前の管理を保てます。"],
    ["Notes, tags, search and sorting", "Notas, etiquetas, búsqueda y ordenación", "Notes, etiquetes, cerca i ordenació", "Notes, étiquettes, recherche et tri", "Notizen, Tags, Suche und Sortierung", "笔记、标签、搜索和排序", "メモ、タグ、検索、並べ替え"],
    ["Local Markdown, CSV and HTML exports", "Exportaciones locales en Markdown, CSV y HTML", "Exportacions locals en Markdown, CSV i HTML", "Exports locaux Markdown, CSV et HTML", "Lokale Markdown-, CSV- und HTML-Exporte", "本地 Markdown、CSV 和 HTML 导出", "ローカルの Markdown、CSV、HTML エクスポート"],
    ["No account required", "No requiere cuenta", "No cal cap compte", "Aucun compte requis", "Kein Konto erforderlich", "无需账户", "アカウント不要"],
    ["Personal, work, university and custom profiles", "Perfiles personales, de trabajo, universidad y personalizados", "Perfils personals, de feina, universitat i personalitzats", "Profils personnels, professionnels, universitaires et personnalisés", "Persönliche, berufliche, universitäre und benutzerdefinierte Profile", "个人、工作、大学和自定义档案", "個人・仕事・大学・カスタムプロフィール"],
    ["Skips passwords, payments and consent fields", "Omite contraseñas, pagos y campos de consentimiento", "Omet contrasenyes, pagaments i camps de consentiment", "Ignore les mots de passe, paiements et champs de consentement", "Überspringt Passwörter, Zahlungen und Einwilligungsfelder", "跳过密码、支付和同意字段", "パスワード、支払い、同意項目をスキップ"],
    ["Never submits a form automatically", "Nunca envía un formulario automáticamente", "Mai envia cap formulari automàticament", "N'envoie jamais un formulaire automatiquement", "Sendet niemals automatisch ein Formular ab", "绝不自动提交表单", "フォームを自動送信しません"],
    ["Save selected tabs as local packs, add notes and tags, return to the full context later, and export your work when you need it.", "Guarda pestañas seleccionadas como packs locales, añade notas y etiquetas, vuelve al contexto completo después y exporta tu trabajo cuando lo necesites.", "Desa pestanyes seleccionades com a packs locals, afegeix notes i etiquetes, torna al context complet més tard i exporta la feina quan calgui.", "Enregistrez des onglets sélectionnés comme packs locaux, ajoutez des notes et étiquettes, retrouvez le contexte complet plus tard et exportez votre travail au besoin.", "Speichern Sie ausgewählte Tabs als lokale Pakete, fügen Sie Notizen und Tags hinzu, kehren Sie später zum vollständigen Kontext zurück und exportieren Sie Ihre Arbeit bei Bedarf.", "将选中的标签页保存为本地资料包，添加笔记和标签，之后恢复完整上下文，并在需要时导出工作内容。", "選択したタブをローカルパックとして保存し、メモとタグを追加。後で完全な文脈に戻り、必要なときにエクスポートできます。"],
    ["Create editable local profiles, link them to websites, and choose whether to review or safely fill recognised fields automatically. Forms are never submitted for you.", "Crea perfiles locales editables, vincúlalos a webs y elige entre revisar o rellenar automáticamente los campos reconocidos de forma segura. Los formularios nunca se envían por ti.", "Crea perfils locals editables, vincula'ls a webs i tria entre revisar o emplenar automàticament els camps reconeguts de manera segura. Els formularis mai s'envien per tu.", "Créez des profils locaux modifiables, liez-les aux sites et choisissez de vérifier ou de remplir automatiquement les champs reconnus en toute sécurité. Les formulaires ne sont jamais envoyés à votre place.", "Erstellen Sie bearbeitbare lokale Profile, verknüpfen Sie sie mit Websites und wählen Sie zwischen Prüfung und sicherem automatischem Ausfüllen erkannter Felder. Formulare werden nie für Sie abgesendet.", "创建可编辑的本地档案，将其关联到网站，并选择检查或安全地自动填写已识别字段。表单绝不会替你提交。", "編集可能なローカルプロフィールを作成してサイトに関連付け、認識項目を確認するか安全に自動入力するかを選べます。フォームが代わりに送信されることはありません。"]
  ];

  rows.push(
    ["Free vs Pro", "Free vs Pro", "Free vs Pro", "Free vs Pro", "Free vs Pro", "Free 与 Pro", "Free と Pro"],
    ["Start useful. Upgrade when repetition becomes routine.", "Empieza siendo útil. Mejora cuando la repetición se convierta en rutina.", "Comença sent útil. Millora quan la repetició es converteixi en rutina.", "Utile dès le départ. Passez à Pro lorsque la répétition devient votre quotidien.", "Von Anfang an nützlich. Pro, wenn Wiederholungen zur Routine werden.", "免费版即刻有用，重复工作成为日常时再升级。", "無料でもすぐ便利。繰り返し作業が日常になったら Pro へ。"],
    ["Free covers everyday filling. Pro is built for people who use forms as part of their real workflow.", "Free cubre el rellenado diario. Pro está pensado para quienes utilizan formularios como parte de su trabajo real.", "Free cobreix l’emplenament diari. Pro està pensat per a qui utilitza formularis com a part de la feina real.", "Free couvre les besoins quotidiens. Pro s’adresse à celles et ceux qui utilisent les formulaires dans leur vrai flux de travail.", "Free deckt den Alltag ab. Pro ist für Menschen, die Formulare fest in ihrem Arbeitsablauf nutzen.", "Free 满足日常填写需求，Pro 面向将表单作为真实工作流程一部分的用户。", "Free は日常の入力に対応。Pro はフォームを実務で繰り返し使う人向けです。"],
    ["From €2.99", "Desde 2,99 €", "Des de 2,99 €", "À partir de 2,99 €", "Ab 2,99 €", "每月 2.99 € 起", "月額 2.99 € から"],
    ["per month · €24.99 per year", "al mes · 24,99 € al año", "al mes · 24,99 € l’any", "par mois · 24,99 € par an", "pro Monat · 24,99 € pro Jahr", "每月 · 每年 24.99 €", "月額 · 年額 24.99 €"],
    ["What you get", "Qué incluye", "Què inclou", "Ce qui est inclus", "Leistungsumfang", "包含内容", "利用できる内容"],
    ["Free", "Free", "Free", "Free", "Free", "Free", "Free"],
    ["Pro", "Pro", "Pro", "Pro", "Pro", "Pro", "Pro"],
    ["Recommended", "Recomendado", "Recomanat", "Recommandé", "Empfohlen", "推荐", "おすすめ"],
    ["Best value", "Mejor opción", "Millor opció", "Meilleur choix", "Bestes Angebot", "最佳选择", "最もお得"],
    ["Form fills", "Rellenados de formularios", "Emplenaments de formularis", "Formulaires remplis", "Formularausfüllungen", "表单填写次数", "フォーム入力"],
    ["10 per day", "10 al día", "10 al dia", "10 par jour", "10 pro Tag", "每天 10 次", "1日10回"],
    ["Unlimited", "Ilimitados", "Il·limitats", "Illimités", "Unbegrenzt", "无限", "無制限"],
    ["Basic local profiles", "Perfiles locales básicos", "Perfils locals bàsics", "Profils locaux de base", "Lokale Basisprofile", "基础本地资料", "基本ローカルプロフィール"],
    ["Included", "Incluido", "Inclòs", "Inclus", "Enthalten", "包含", "利用可能"],
    ["Not included", "No incluido", "No inclòs", "Non inclus", "Nicht enthalten", "不包含", "利用不可"],
    ["Smart field detection", "Detección inteligente de campos", "Detecció intel·ligent de camps", "Détection intelligente des champs", "Intelligente Felderkennung", "智能字段检测", "スマートな項目検出"],
    ["Rules for each website", "Reglas para cada web", "Regles per a cada web", "Règles pour chaque site", "Regeln für jede Website", "每个网站的规则", "サイトごとのルール"],
    ["Learned field corrections", "Correcciones de campos aprendidas", "Correccions de camps apreses", "Corrections de champs mémorisées", "Gelernte Feldkorrekturen", "已学习的字段更正", "学習済みの項目修正"],
    ["Advanced CV profiles", "Perfiles CV avanzados", "Perfils de CV avançats", "Profils CV avancés", "Erweiterte Lebenslaufprofile", "高级简历资料", "高度な履歴書プロフィール"],
    ["Reusable answers across profiles", "Respuestas reutilizables entre perfiles", "Respostes reutilitzables entre perfils", "Réponses réutilisables entre les profils", "Profilübergreifend wiederverwendbare Antworten", "跨资料重复使用的答案", "プロフィール共通の再利用回答"],
    ["CSV profile import", "Importación de perfiles CSV", "Importació de perfils CSV", "Import de profils CSV", "CSV-Profilimport", "CSV 资料导入", "CSV プロフィール読み込み"],
    ["Private activity history", "Historial privado de actividad", "Historial privat d’activitat", "Historique d’activité privé", "Privater Aktivitätsverlauf", "私密活动历史", "非公開のアクティビティ履歴"],
    ["90 days", "90 días", "90 dies", "90 jours", "90 Tage", "90 天", "90日"],
    ["Your profiles stay local in both plans.", "Tus perfiles permanecen locales en ambos planes.", "Els perfils continuen sent locals en tots dos plans.", "Vos profils restent locaux avec les deux offres.", "Ihre Profile bleiben in beiden Tarifen lokal.", "两个版本都会将资料保存在本地。", "どちらのプランでもプロフィールはローカルに保存されます。"],
    ["Choose monthly or annual billing in the secure ExtensionPay checkout.", "Elige facturación mensual o anual en el pago seguro de ExtensionPay.", "Tria facturació mensual o anual al pagament segur d’ExtensionPay.", "Choisissez la facturation mensuelle ou annuelle dans le paiement sécurisé d’ExtensionPay.", "Wählen Sie monatliche oder jährliche Abrechnung im sicheren ExtensionPay-Checkout.", "请在 ExtensionPay 安全结账页面选择月付或年付。", "ExtensionPay の安全な決済画面で月払いまたは年払いを選択できます。"],
    ["Get AutoFill Pro", "Conseguir AutoFill Pro", "Aconsegueix AutoFill Pro", "Obtenir AutoFill Pro", "AutoFill Pro holen", "获取 AutoFill Pro", "AutoFill Pro を入手"],
    ["Keep collecting for free. Go Pro when the sources need to become research.", "Sigue recopilando gratis. Pásate a Pro cuando las fuentes tengan que convertirse en investigación.", "Continua recopilant gratis. Passa a Pro quan les fonts s’hagin de convertir en recerca.", "Continuez à collecter gratuitement. Passez à Pro lorsque vos sources doivent devenir une vraie recherche.", "Sammeln Sie kostenlos weiter. Pro macht aus Quellen echte Recherche.", "继续免费收集，需要将来源变成研究成果时再升级 Pro。", "収集は無料のまま。情報源をリサーチに変えるときに Pro へ。"],
    ["The essential pack workflow stays free. Pro adds the tools that help you read, understand, cite and reuse what you save.", "El flujo esencial de packs sigue siendo gratuito. Pro añade las herramientas para leer, entender, citar y reutilizar lo que guardas.", "El flux essencial de packs continua sent gratuït. Pro afegeix les eines per llegir, entendre, citar i reutilitzar el que deses.", "Le flux essentiel des packs reste gratuit. Pro ajoute les outils pour lire, comprendre, citer et réutiliser vos sources.", "Der grundlegende Pack-Workflow bleibt kostenlos. Pro hilft beim Lesen, Verstehen, Zitieren und Wiederverwenden.", "核心资料包流程永久免费，Pro 提供阅读、理解、引用和重复利用所保存内容的工具。", "基本のパック機能は無料。Pro では保存した内容を読み、理解し、引用し、再利用できます。"],
    ["one-time payment · lifetime local Pro", "pago único · Pro local de por vida", "pagament únic · Pro local per sempre", "paiement unique · Pro local à vie", "Einmalzahlung · lokales Pro auf Lebenszeit", "一次性付款 · 终身本地 Pro", "買い切り · ローカル Pro を永久利用"],
    ["Saved packs", "Packs guardados", "Packs desats", "Dossiers enregistrés", "Gespeicherte Sammlungen", "已保存资料包", "保存できるパック"],
    ["Up to 10", "Hasta 10", "Fins a 10", "Jusqu’à 10", "Bis zu 10", "最多 10 个", "最大10件"],
    ["Projects and duplicate control", "Proyectos y control de duplicados", "Projectes i control de duplicats", "Projets et contrôle des doublons", "Projekte und Duplikatkontrolle", "项目与重复项管理", "プロジェクトと重複管理"],
    ["Pack notes, tags, search and sorting", "Notas, etiquetas, búsqueda y ordenación de packs", "Notes, etiquetes, cerca i ordenació de packs", "Notes, étiquettes, recherche et tri des dossiers", "Notizen, Tags, Suche und Sortierung", "资料包备注、标签、搜索和排序", "パックのメモ、タグ、検索、並べ替え"],
    ["JSON, Markdown, CSV and HTML exports", "Exportaciones JSON, Markdown, CSV y HTML", "Exportacions JSON, Markdown, CSV i HTML", "Exports JSON, Markdown, CSV et HTML", "JSON-, Markdown-, CSV- und HTML-Exporte", "JSON、Markdown、CSV 和 HTML 导出", "JSON、Markdown、CSV、HTML 書き出し"],
    ["Notes for every source", "Notas para cada fuente", "Notes per a cada font", "Notes pour chaque source", "Notizen für jede Quelle", "每个来源的备注", "情報源ごとのメモ"],
    ["Automatic source metadata", "Metadatos automáticos por fuente", "Metadades automàtiques per font", "Métadonnées automatiques par source", "Automatische Quellenmetadaten", "自动来源元数据", "情報源メタデータの自動取得"],
    ["APA, MLA, BibTeX and RIS citations", "Citas APA, MLA, BibTeX y RIS", "Citacions APA, MLA, BibTeX i RIS", "Citations APA, MLA, BibTeX et RIS", "APA-, MLA-, BibTeX- und RIS-Zitate", "APA、MLA、BibTeX 和 RIS 引用", "APA・MLA・BibTeX・RIS 引用"],
    ["Research templates", "Plantillas de investigación", "Plantilles de recerca", "Modèles de recherche", "Recherchevorlagen", "研究模板", "リサーチテンプレート"],
    ["Clean reading view", "Vista de lectura limpia", "Vista de lectura neta", "Mode lecture épuré", "Saubere Leseansicht", "纯净阅读视图", "クリーンな読書ビュー"],
    ["Local multi-source summaries", "Resúmenes locales de varias fuentes", "Resums locals de diverses fonts", "Résumés locaux de plusieurs sources", "Lokale Zusammenfassungen mehrerer Quellen", "本地多来源摘要", "複数情報源のローカル要約"],
    ["PDF export", "Exportación PDF", "Exportació PDF", "Export PDF", "PDF-Export", "PDF 导出", "PDF 書き出し"],
    ["Your packs stay local in both plans.", "Tus packs permanecen locales en ambos planes.", "Els packs continuen sent locals en tots dos plans.", "Vos dossiers restent locaux avec les deux offres.", "Ihre Sammlungen bleiben in beiden Tarifen lokal.", "两个版本都会将资料包保存在本地。", "どちらのプランでもパックはローカルに保存されます。"],
    ["One payment unlocks all current local Pro features.", "Un solo pago desbloquea todas las funciones Pro locales actuales.", "Un sol pagament desbloqueja totes les funcions Pro locals actuals.", "Un seul paiement débloque toutes les fonctions Pro locales actuelles.", "Eine Zahlung schaltet alle aktuellen lokalen Pro-Funktionen frei.", "一次付款即可解锁当前所有本地 Pro 功能。", "1回の支払いで現在のローカル Pro 機能をすべて利用できます。"],
    ["Get Research Packs Pro", "Conseguir Research Packs Pro", "Aconsegueix Research Packs Pro", "Obtenir Research Packs Pro", "Research Packs Pro holen", "获取 Research Packs Pro", "Research Packs Pro を入手"]
  );

  const baseLanguages = ["en", "es", "ca", "fr", "de", "zh_CN", "ja"];
  const translations = Object.fromEntries(baseLanguages.map((language, index) => [language, Object.fromEntries(rows.map(row => [row[0], row[index]]))]));
  const extraTranslations = window.PRODUCTIVITY_SUITE_EXTRA_TRANSLATIONS || {};
  ["es", "ca", "fr", "de", "it", "pt", "nl", "ja", "zh_CN"].forEach((language) => {
    translations[language] = { ...(translations[language] || {}), ...(extraTranslations[language] || {}) };
  });
  const storageKey = "productivity-suite-language";

  const prepareTextNodes = () => {
    document.querySelectorAll("body *").forEach(element => {
      if (element.closest("script, style") || element.matches("option, .visually-hidden")) return;
      if (element.children.length || !element.textContent.trim()) return;
      if (!element.dataset.i18nSource) element.dataset.i18nSource = element.textContent.trim();
    });
  };

  const setLanguage = language => {
    const normalized = language === "zh" || language?.toLowerCase().startsWith("zh") ? "zh_CN"
      : language === "pt_BR" || language?.toLowerCase().startsWith("pt-") ? "pt"
      : String(language || "en").slice(0, 2).toLowerCase();
    const selected = translations[normalized] ? normalized : "en";
    const dictionary = translations[selected];
    document.documentElement.lang = selected;
    document.querySelectorAll("[data-i18n-source]").forEach(element => {
      const source = element.dataset.i18nSource;
      element.textContent = dictionary[source] || source;
    });
    document.querySelectorAll("[data-language-selector]").forEach(select => { select.value = selected; });
    localStorage.setItem(storageKey, selected);
    document.dispatchEvent(new CustomEvent("productivitysuite:languagechange", { detail: { language: selected } }));
  };

  prepareTextNodes();
  const requested = new URLSearchParams(window.location.search).get("lang");
  const initial = requested || localStorage.getItem(storageKey) || navigator.language || "en";
  setLanguage(initial);
  document.querySelectorAll("[data-language-selector]").forEach(select => select.addEventListener("change", event => setLanguage(event.target.value)));
})();
